import { existsSync, readFileSync, writeFileSync } from 'node:fs';

function normalizeSkillRef(ref) {
  const v = ref.trim();

  // Support full ClawHub URL: https://clawhub.ai/<owner>/<slug>
  if (v.startsWith('http://') || v.startsWith('https://')) {
    try {
      const u = new URL(v);
      const parts = u.pathname.split('/').filter(Boolean);
      if (parts.length >= 2) return parts[parts.length - 1];
    } catch {
      // fallthrough
    }
  }

  // Support owner/slug shorthand by taking slug
  if (v.includes('/') && !v.includes(' ')) {
    const parts = v.split('/').filter(Boolean);
    if (parts.length >= 2) return parts[parts.length - 1];
  }

  return v;
}

export function parseFile(path) {
  const directives = {};
  const skills = [];
  const lines = readFileSync(path, 'utf8').split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.split('#')[0].trim();
    if (!line) continue;
    if (line.startsWith('registry ')) {
      directives.registry = line.slice('registry '.length).trim();
      continue;
    }
    if (line.startsWith('workdir ')) {
      directives.workdir = line.slice('workdir '.length).trim();
      continue;
    }

    const normalized = normalizeSkillRef(line);
    const idx = normalized.lastIndexOf('@');
    if (idx > 0) skills.push({ slug: normalized.slice(0, idx), version: normalized.slice(idx + 1) });
    else skills.push({ slug: normalized, version: '' });
  }
  return { directives, skills };
}

export function loadLock(lockPath) {
  if (!existsSync(lockPath)) return new Map();
  const { skills } = parseFile(lockPath);
  const map = new Map();
  for (const s of skills) map.set(s.slug, s.version);
  return map;
}

export function writeLock(lockPath, directives, skills, installedMap) {
  const lines = [
    `# Auto-generated by clawfile`,
    `# ${new Date().toISOString()}`,
  ];
  if (directives.registry) lines.push(`registry ${directives.registry}`);
  if (directives.workdir) lines.push(`workdir ${directives.workdir}`);
  lines.push('');
  for (const s of skills) {
    const v = installedMap.get(s.slug) || s.version;
    lines.push(v ? `${s.slug}@${v}` : s.slug);
  }
  writeFileSync(lockPath, `${lines.join('\n')}\n`, 'utf8');
}
